### ISSUE TITLE
Tags are only saved when beforeSave() method is present

### ISSUE THREAD

**Issue by zeitgeist13** [2amigos/yii2-taggable-behavior#10]
After the last update, my tags didn't save anymore. 

I debugged it and found out that the tagValues property in the Taggable class was null.

For further debugging I added the beforeSave() method to the model implementing the TaggableBehavior, and then it worked again. 

Is it for some reason neccessary to do that?

**Comment by tonydspaniard** [comment]
The reason is that tagValues is null because we thought that is pointless to populate the relation if its not being used. Only when used will be filled in.

**Comment by tonydspaniard** [comment]
@zeitgeist13 there was an issue with our update. I have to fix the extension making a good review of it

**Comment by creocoder** [comment]
@zeitgeist13 Please check last 1.0.0 release.

**Comment by gooGooGaJoob** [comment]
I had a similar problem. Assigning and un-Assigning tags to records worked fine. But new tags were not being created.

The problem was that the ID was not defined so the new tag record did not pass the validation.

I got it to work by:
* Removing 'id' from the required list of attributes in my Tag Model Class
* Changing the DB to Auto-Increment for the ID

Is this the way things are supposed to work?

**Comment by creocoder** [comment]
@gooGooGaJoob Yes, you don't need any validator for `id`. Its possible to make it not auto-increment, but in general it designed for usual primary key definition (integer, auto-increment).

**Comment by zeitgeist13** [comment]
everything works fine now, thank you.
